import type { EventName } from "@/lib/types";

/**
 * DTM-side internal milestone calendar — what DTM itself owes/must do to run
 * DTM27 and SPARTA27 on schedule, as opposed to lib/deadline-schedule.ts's
 * SCHEDULED_DEADLINES (what a PARTNER owes DTM). Sourced from the "CS
 * Timeline | DTM27 & SPARTA27" Notion database (CS Playbook → 4 · Delivery
 * timeline) — that page is the source of truth. To change a date, owner,
 * detail or add/remove a milestone, edit it there and ask for a re-sync
 * rather than editing this file by hand: https://app.notion.com/p/deep-tech-momentum/a3b42beac2ea4badbb32c8943bd9ee0a
 *
 * Every row already carries a real calendar date (Notion's "Date" column,
 * already resolved from the Playbook's week-numbering against each event's
 * T-0) — "weeksOut" is kept only as the original relative-week context, not
 * something this app needs to recompute.
 *
 * Synced 2026-09-22.
 */

export type DtmDeliverableEvent = "DTM27" | "SPARTA27" | "Both";

export interface DtmDeliverable {
  /** Stable id derived from the Notion page's URL — used as the primary key for persisted status (see lib/dtm-deliverable-status.ts). */
  id: string;
  milestone: string;
  detail: string;
  event: DtmDeliverableEvent;
  /** One of the ten Notion "Workstream" options — see workstreamDisplayName() in lib/portal-view.ts for the one naming mismatch against Attio's own Workstream type (lib/portal-config.ts). */
  workstream: string;
  ownerRole: string;
  phase: "Onboarding" | "Fulfilment" | "Event" | "Wrap";
  weeksOut: number;
  hardWall: boolean;
  inProjectPlan: boolean;
  partnerFacing: boolean;
  /** ISO date. */
  date: string;
  dateEnd: string | null;
  notionUrl: string;
}

/** Maps this file's Notion-native event label onto the app's own EventName ("SPARTA 2027", not "SPARTA27"). "Both" milestones apply whenever the partner is in either event. */
export function dtmDeliverableAppliesToEvents(deliverable: DtmDeliverable, portalEvents: EventName[]): boolean {
  if (deliverable.event === "Both") {
    return portalEvents.includes("DTM27") || portalEvents.includes("SPARTA 2027");
  }
  const wanted: EventName = deliverable.event === "SPARTA27" ? "SPARTA 2027" : "DTM27";
  return portalEvents.includes(wanted);
}

export const DTM_DELIVERABLES: DtmDeliverable[] = [
  {
    id: "3cc9551435718178a6efcfa01e7ae682",
    milestone: "Applications launch",
    detail: "SPARTA runs an application-based attendee model. Partners need to know their guests apply rather than simply buy.",
    event: "SPARTA27",
    workstream: "Passes & Access",
    ownerRole: "Passes & Access Owner",
    phase: "Onboarding",
    weeksOut: 24,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-08-24",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718178a6efcfa01e7ae682",
  },
  {
    id: "3cc95514357181f986f4d2d0ed94baa6",
    milestone: "Share exhibitor guidelines",
    detail: "Does not exist for any year. Every partner-facing spec hangs off it.",
    event: "SPARTA27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Onboarding",
    weeksOut: 18,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-10-05",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181f986f4d2d0ed94baa6",
  },
  {
    id: "3cc95514357181a4b7fed567e7ecd616",
    milestone: "Alignment on paid 1:1 meetings",
    detail: "In both the Partnership and Matchmaking lanes. For most SPARTA partners the 1:1s are the product, so this is the deliverable.",
    event: "SPARTA27",
    workstream: "Matchmaking / Product",
    ownerRole: "Matchmaking Owner",
    phase: "Fulfilment",
    weeksOut: 17,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: false,
    date: "2026-10-12",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181a4b7fed567e7ecd616",
  },
  {
    id: "3cc95514357181cea5efe78d7135bf27",
    milestone: "Share exhibitor guidelines",
    detail: "Does not exist. Every partner-facing spec and the master action email link to it, so nothing partner-facing is complete until it is written.",
    event: "DTM27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Onboarding",
    weeksOut: 27,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-11-02",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181cea5efe78d7135bf27",
  },
  {
    id: "3cc95514357181b4948be8fe558ea8b0",
    milestone: "Agenda finalised, full agenda on website",
    detail: "After this a partner session cannot be added or moved without a cascade. Also this week: meeting logistics and purchase flow finalised.",
    event: "SPARTA27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 14,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-11-02",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181b4948be8fe558ea8b0",
  },
  {
    id: "3cc95514357181a7b1c2f3255fc3a7d4",
    milestone: "Speaker onboarding complete",
    detail: "Headshot, bio, title, mobile, form complete for every partner-supplied speaker. Attendee 1:1 scheduling also begins this week.",
    event: "SPARTA27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 13,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-11-09",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181a7b1c2f3255fc3a7d4",
  },
  {
    id: "3cc95514357181399993ea57d2ddbccd",
    milestone: "Speaker preparation email sent",
    detail: "Template 10 in the comms library.",
    event: "SPARTA27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 12,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-11-16",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181399993ea57d2ddbccd",
  },
  {
    id: "3cc95514357181849ce8dde8e0d8ff87",
    milestone: "Early Bird tickets live",
    detail: "Website hard launch W25 (16.11), Early Bird W24. Early Bird is the floor for partner rates on additional tickets, so this fixes what CS can quote.",
    event: "DTM27",
    workstream: "Passes & Access",
    ownerRole: "Passes & Access Owner",
    phase: "Onboarding",
    weeksOut: 24,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-11-23",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181849ce8dde8e0d8ff87",
  },
  {
    id: "3cc9551435718108a205e4efff591c82",
    milestone: "Speaker briefings and deck collection begin",
    detail: "Runs W10 to W8 (30.11 – 14.12.2026). Also W10: floor plan finalised. Chase partner artwork this fortnight too — December is holiday.",
    event: "SPARTA27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 10,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-11-30",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718108a205e4efff591c82",
  },
  {
    id: "3cc955143571818899b5cdbe748b04c8",
    milestone: "Partners for programmes confirmed",
    detail: "Which partner holds which programme slot. The contractual wording says speaking slots are confirmed before 01.12.2026 and subject to editorial alignment.",
    event: "DTM27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Onboarding",
    weeksOut: 21,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-12-14",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571818899b5cdbe748b04c8",
  },
  {
    id: "3cc955143571816da140cee36c26f263",
    milestone: "Close partnership matchmaking + close applications",
    detail: "Names of everyone attending are needed by this date. Partner 1:1 scheduling starts here and runs to W5.",
    event: "SPARTA27",
    workstream: "Matchmaking / Product",
    ownerRole: "Matchmaking Owner",
    phase: "Fulfilment",
    weeksOut: 7,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-12-21",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571816da140cee36c26f263",
  },
  {
    id: "3cc9551435718199a1abf82b87db834e",
    milestone: "Graphic submission deadline",
    detail: "HARD WALL, in the week the plan marks \"EOY Holiday Season\". No recovery week behind it.",
    event: "SPARTA27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Fulfilment",
    weeksOut: 7,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2026-12-21",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718199a1abf82b87db834e",
  },
  {
    id: "3cc9551435718189aa9dde0dd8845ce5",
    milestone: "Unsold programming inventory cut-off",
    detail: "Plan wording, verbatim: \"No new ideas - Killing unsold houses\". Anything a partner is still considering has to be closed before here or it stops existing.",
    event: "DTM27",
    workstream: "Content & Programming",
    ownerRole: "Sales Lead",
    phase: "Onboarding",
    weeksOut: 19,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: false,
    date: "2026-12-28",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718189aa9dde0dd8845ce5",
  },
  {
    id: "3cc9551435718108b11dfd7e896e4f2b",
    milestone: "Close sales",
    detail: "Runs W6 to W4. Final close is W3.",
    event: "SPARTA27",
    workstream: "Sales",
    ownerRole: "Sales Lead",
    phase: "Fulfilment",
    weeksOut: 6,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: false,
    date: "2026-12-28",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718108b11dfd7e896e4f2b",
  },
  {
    id: "3cc95514357181058cece355a9ee3106",
    milestone: "Print submission deadline",
    detail: "HARD WALL. Two weeks after graphics with Christmas in between — effectively no slack.",
    event: "SPARTA27",
    workstream: "Branding & Design",
    ownerRole: "Branding & Design Owner",
    phase: "Fulfilment",
    weeksOut: 5,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: false,
    date: "2027-01-04",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181058cece355a9ee3106",
  },
  {
    id: "3cc95514357181d68953cd09725f3027",
    milestone: "Matchmaking platform goes live",
    detail: "CONFLICT: the SPARTA plan says 04.01.2027, the DTM27 plan says 18.01.2027. Resolve before promising a date. Invitations come from a noreply address — warn partners to check spam.",
    event: "SPARTA27",
    workstream: "Matchmaking / Product",
    ownerRole: "Matchmaking Owner",
    phase: "Fulfilment",
    weeksOut: 5,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-01-04",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181d68953cd09725f3027",
  },
  {
    id: "3cc95514357181249daad3a215122e17",
    milestone: "Onboarding wave — portals live, welcomes sent, codes issued",
    detail: "Deliberately in the same week as the plan's CS preparation kick-off and deliberately before SPARTA. Every partner signed to date gets a configured portal, a welcome email, ticket codes and pass types.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Onboarding",
    weeksOut: 16,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-01-18",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181249daad3a215122e17",
  },
  {
    id: "3cc955143571812e99ddcbb58243b4c7",
    milestone: "Customer success preparation kick-off",
    detail: "The only dated CS milestone for DTM27 in the plan. Everything below this line is CS-set, because the plan's CUSTOMER SUCCESS and SPONSOR DELIVERABLES sections are empty placeholders.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Onboarding",
    weeksOut: 16,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: false,
    date: "2027-01-18",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571812e99ddcbb58243b4c7",
  },
  {
    id: "3cc95514357181248dd6c12227be0e65",
    milestone: "Slide deck deadline",
    detail: "HARD WALL. The plan lists this twice — Content lane W3 (18.01), Key Milestones W1 (01.02). Use the earlier date with partners; W1 is the internal check.",
    event: "SPARTA27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 3,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-01-18",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181248dd6c12227be0e65",
  },
  {
    id: "3cc9551435718197a629d67588585d5f",
    milestone: "Sales close — FINAL",
    detail: "Last date a partner can enter the SPARTA cycle. Anything sold here has already missed graphic and print — sell it with a written note of what cannot be delivered.",
    event: "SPARTA27",
    workstream: "Sales",
    ownerRole: "Sales Lead",
    phase: "Fulfilment",
    weeksOut: 3,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: false,
    date: "2027-01-18",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718197a629d67588585d5f",
  },
  {
    id: "3cc95514357181599e43da4df518a10b",
    milestone: "Intro calls held, logo and company description in",
    detail: "Logo all-white in .svg/.eps/.pdf/.ai plus a click-through URL and designer sign-off; description 250 characters. Both gate the website, agenda, app and print chain.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Onboarding",
    weeksOut: 15,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-01-25",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181599e43da4df518a10b",
  },
  {
    id: "3cc95514357181149cf1e6bf8ffbb151",
    milestone: "Customer success deliverables",
    detail: "Plan wording: \"Customer success deliverables\", Partnership lane at W2 and W1 (25.01 and 01.02.2027). The fortnight where everything owed gets closed before the event.",
    event: "SPARTA27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Fulfilment",
    weeksOut: 2,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-01-25",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181149cf1e6bf8ffbb151",
  },
  {
    id: "3cc9551435718168b20fe0e24f0c09cb",
    milestone: "Profile activation deadline",
    detail: "Preferences freeze so curation can run. Unactivated tickets go to the waiting list — say so plainly.",
    event: "SPARTA27",
    workstream: "Matchmaking / Product",
    ownerRole: "Matchmaking Owner",
    phase: "Fulfilment",
    weeksOut: 2,
    hardWall: true,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-01-28",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718168b20fe0e24f0c09cb",
  },
  {
    id: "3cc955143571813cb499fe11859f8db0",
    milestone: "100% agenda close; speakers, moderators, stage hosts complete",
    detail: "HARD WALL for content partners. A session cannot be added after this, and moving one cascades into the website, the app and the partner's own comms.",
    event: "DTM27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 14,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-02-01",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571813cb499fe11859f8db0",
  },
  {
    id: "3cc95514357181179efcfee2c3221ea6",
    milestone: "Final logistics email",
    detail: "Photo ID matching the ticket name, bag policy, security checkpoints, hard start time, dress code. Template 12. Joint send with TUM Venture Labs.",
    event: "SPARTA27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Fulfilment",
    weeksOut: 1,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-02-04",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181179efcfee2c3221ea6",
  },
  {
    id: "3cc9551435718172a3a8e79c7c895ae0",
    milestone: "Speaker preparation email sent",
    detail: "Template 10.",
    event: "DTM27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 13,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-02-08",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718172a3a8e79c7c895ae0",
  },
  {
    id: "3cc95514357181d585cce87ca6e83c3e",
    milestone: "1:1s confirmed in calendars",
    detail: "Two days out, 19:00 CET. Unconfirmed slots are reassigned so the room stays full. Physical items at the venue the same day.",
    event: "SPARTA27",
    workstream: "Matchmaking / Product",
    ownerRole: "Matchmaking Owner",
    phase: "Event",
    weeksOut: 0,
    hardWall: true,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-02-09",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181d585cce87ca6e83c3e",
  },
  {
    id: "3cc95514357181fc987ce06488a18016",
    milestone: "LIVE",
    detail: "T-0 week w/c 08.02.2027. Munich, official side event of the Munich Security Conference, co-organised with TUM Venture Labs. Note: the DTM27 plan blocks w/c 15.02.2027 as SPARTA week, a week later than SPARTA's own plan.",
    event: "SPARTA27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Event",
    weeksOut: 0,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-02-11",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181fc987ce06488a18016",
  },
  {
    id: "3cc9551435718162b908e3f0f5df3f11",
    milestone: "Roundtable and activation data delivered",
    detail: "HARD WALL — contractual. The package wording promises attendees scanned in and data shared 72h post-SPARTA.",
    event: "SPARTA27",
    workstream: "Passes & Access",
    ownerRole: "Passes & Access Owner",
    phase: "Wrap",
    weeksOut: -0.4,
    hardWall: true,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-02-14",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718162b908e3f0f5df3f11",
  },
  {
    id: "3cc95514357181abb013fc37bae60d93",
    milestone: "delivery week — DTM27 CS capacity blocked",
    detail: "The DTM27 plan writes \"SPARTA 2027\" across every lane for this week. SPARTA's own plan puts its live week a week earlier. Either way, early-to-mid February is not available for DTM27 onboarding.",
    event: "Both",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Fulfilment",
    weeksOut: 12,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: false,
    date: "2027-02-15",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181abb013fc37bae60d93",
  },
  {
    id: "3cc9551435718118a2f0e04f724c6b06",
    milestone: "Follow-ups, post-event email + survey",
    detail: "Plan W-1: dismantle, follow-ups, post-event wrap up, post-event meeting surveys and report.",
    event: "SPARTA27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Wrap",
    weeksOut: -1,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-02-15",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718118a2f0e04f724c6b06",
  },
  {
    id: "3cc9551435718118bc22d80c1a052de0",
    milestone: "Booth confirmed per partner — type, size, unit, market, lead scanning",
    detail: "Four weeks ahead of the turnkey design deadline. Ask about oversize demos, additional voltage and external F&B here — all three need prior approval. Confirm whether Lead Scanner Hire is in or explicitly declined.",
    event: "DTM27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Fulfilment",
    weeksOut: 11,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-02-22",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718118bc22d80c1a052de0",
  },
  {
    id: "3cc95514357181c48f38deafce13c051",
    milestone: "Speaker onboarding complete",
    detail: "Headshot, bio, title, mobile for every partner-supplied speaker. Chase from early February. Speaker directory completes 01.03.2027.",
    event: "DTM27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 11,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-02-22",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181c48f38deafce13c051",
  },
  {
    id: "3cc955143571815390c2eae3f7e92540",
    milestone: "Post-event report, NPS, event media shared",
    detail: "The plan marks this week \"Winter Holiday\" — either it goes out before the break or it slips to March.",
    event: "SPARTA27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Wrap",
    weeksOut: -2,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-02-22",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571815390c2eae3f7e92540",
  },
  {
    id: "3cc9551435718183b107d449c58ee63e",
    milestone: "Add-ons menu sent, mockups shared, selection locked",
    detail: "One week before the plan closes turnkey and catering sales. Send the mockup with the exact production dimensions — partners design to visible dimensions and lose 20mm of their logo.",
    event: "DTM27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Fulfilment",
    weeksOut: 10,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-03-01",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718183b107d449c58ee63e",
  },
  {
    id: "3cc95514357181c1b76cfa07b9bbaf99",
    milestone: "All partners at stage Onboarded",
    detail: "Anyone not onboarded by here is Health = Fair at minimum. Partners signing after this follow the late-signer compression in Part 4.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Onboarding",
    weeksOut: 10,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: false,
    date: "2027-03-01",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181c1b76cfa07b9bbaf99",
  },
  {
    id: "3cc955143571810198c8d639cafb4099",
    milestone: "Rebooking into DTM27 opened with every partner",
    detail: "SPARTA lands ten weeks before DTM27 with fresh proof of value, and DTM27's plan has \"Late selling\" running 22.02–05.04.2027. The highest-value rebooking window in the year.",
    event: "SPARTA27",
    workstream: "Sales",
    ownerRole: "Sales Lead",
    phase: "Wrap",
    weeksOut: -3,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-03-01",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571810198c8d639cafb4099",
  },
  {
    id: "3cc95514357181b9ab49d89de288c44a",
    milestone: "All logistics locked; turnkey, catering and add-on sales closed",
    detail: "HARD WALL. After this: no add-ons, no catering, no turnkey changes. Session logistics — duration, room, AV — lock here too.",
    event: "DTM27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Fulfilment",
    weeksOut: 9,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-03-08",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181b9ab49d89de288c44a",
  },
  {
    id: "3cc955143571811fa9a4deed13e1e5a4",
    milestone: "Full agenda on website",
    detail: "Partners check the website for their session and their logo the week it goes live. Make sure both are right before this date.",
    event: "DTM27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 8,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-03-15",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571811fa9a4deed13e1e5a4",
  },
  {
    id: "3cc95514357181da9373e2aae51c0ca8",
    milestone: "Turnkey design deadline",
    detail: "HARD WALL. Turnkey booth designs locked. Speaker briefings and deck collection also begin this week and run to W5.",
    event: "DTM27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Fulfilment",
    weeksOut: 7,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-03-22",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181da9373e2aae51c0ca8",
  },
  {
    id: "3cc95514357181ea91dec2b1215c8320",
    milestone: "Backdrop artwork received + Ops sign-off",
    detail: "CS buffer, one week before the graphic submission deadline, so there is time to reject and resubmit unusable files.",
    event: "DTM27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Fulfilment",
    weeksOut: 7,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-03-22",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181ea91dec2b1215c8320",
  },
  {
    id: "3cc95514357181b58ce6d5cb4dace957",
    milestone: "Graphic submission deadline",
    detail: "HARD WALL. PDF/X-3 or X-4, 20mm bleed all sides, ISO Coated v2 (FOGRA39) or PSO Coated v3 (FOGRA51), no crop or registration marks, fonts embedded. Also this week: agenda closed and speakers live on the website; six-week partner check-in; digital branding placed.",
    event: "DTM27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Fulfilment",
    weeksOut: 6,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-03-29",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181b58ce6d5cb4dace957",
  },
  {
    id: "3cc95514357181229690f267a79239d0",
    milestone: "Print submission deadline",
    detail: "HARD WALL. Nothing arriving after this gets printed — partner walls, badges, lanyards, signage. Artwork must be with CS by 22.03 so there is time to reject and resubmit.",
    event: "DTM27",
    workstream: "Branding & Design",
    ownerRole: "Branding & Design Owner",
    phase: "Fulfilment",
    weeksOut: 5,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: false,
    date: "2027-04-05",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181229690f267a79239d0",
  },
  {
    id: "3cc955143571813e9418f8fce7851925",
    milestone: "Platform + meeting purchase live",
    detail: "Partners build matchmaking profiles from here. Profile completion drives their 1:1s — chase it explicitly. Curation runs the final fortnight because most participants confirm late.",
    event: "DTM27",
    workstream: "Matchmaking / Product",
    ownerRole: "Matchmaking Owner",
    phase: "Fulfilment",
    weeksOut: 5,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-04-05",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571813e9418f8fce7851925",
  },
  {
    id: "3cc9551435718179b0b3e66abba11513",
    milestone: "All sales close",
    detail: "HARD WALL, and it sits a week AFTER print. Anything sold from W9 onwards has already missed logistics, add-ons, turnkey and print — sell it with a written note of what cannot be delivered, agreed before signature. Bespoke sales close W8 (15.03); final closing sits at W1.",
    event: "DTM27",
    workstream: "Sales",
    ownerRole: "Sales Lead",
    phase: "Fulfilment",
    weeksOut: 4,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: false,
    date: "2027-04-12",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718179b0b3e66abba11513",
  },
  {
    id: "3cc95514357181228b88d58ff5d8cfc1",
    milestone: "Slide deck deadline",
    detail: "HARD WALL. The plan contradicts itself — Content lane W3 (19.04), Key Milestones W2 (26.04). Use the earlier date with partners; W2 and W1 are the internal check weeks. Final reminder goes out W4 (12.04).",
    event: "DTM27",
    workstream: "Content & Programming",
    ownerRole: "Content & Programming Owner",
    phase: "Fulfilment",
    weeksOut: 3,
    hardWall: true,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-04-19",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181228b88d58ff5d8cfc1",
  },
  {
    id: "3cc9551435718180a008c38f94b53cf0",
    milestone: "All ticket codes redeemed",
    detail: "CS-set. The plan lists \"Partner pass redemption deadline\" with no date — this fills the gap. Set before regular-price tickets go live the same week, and say plainly that the event oversubscribes.",
    event: "DTM27",
    workstream: "Passes & Access",
    ownerRole: "Passes & Access Owner",
    phase: "Fulfilment",
    weeksOut: 3,
    hardWall: true,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-04-19",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc9551435718180a008c38f94b53cf0",
  },
  {
    id: "3cc95514357181fb90d7f1970898ecfd",
    milestone: "Two-weeks-out partner email",
    detail: "Template 08. Redeem tickets, complete platform profile, share the discount code, plus exhibitor logistics below the signature. Delivery and pick-up windows reported the same week.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Fulfilment",
    weeksOut: 2,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-04-26",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181fb90d7f1970898ecfd",
  },
  {
    id: "3cc95514357181f9b273cc6035c53be8",
    milestone: "Full attendee list collected; final logistics email",
    detail: "Names on badges, no walk-up for partner passes. Template 11: build windows, delivery label, on-site contacts with mobile numbers, registration times, hotel link.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Fulfilment",
    weeksOut: 1,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-05-03",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181f9b273cc6035c53be8",
  },
  {
    id: "3cc95514357181169ab0c0cbed050b4f",
    milestone: "Physical items delivered to venue",
    detail: "HARD WALL — contractual, 48h before day one. Bag inserts and seat drops especially. No storage guaranteed before this window.",
    event: "DTM27",
    workstream: "Exhibition / Booth",
    ownerRole: "On-site Ops Owner",
    phase: "Event",
    weeksOut: 0.3,
    hardWall: true,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-05-10",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181169ab0c0cbed050b4f",
  },
  {
    id: "3cc955143571812884f1ea3c67cef9f8",
    milestone: "Build-up and booth sign-off",
    detail: "Build days run into 11.05. CS walks the floor against a printed partner list before doors open on 12.05 — find the problems before the partner does.",
    event: "DTM27",
    workstream: "Exhibition / Booth",
    ownerRole: "Exhibition & Booth Owner",
    phase: "Event",
    weeksOut: 0.2,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-05-10",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571812884f1ea3c67cef9f8",
  },
  {
    id: "3cc9551435718191bbf3dca1aa666736",
    milestone: "LIVE",
    detail: "Confirmed by the plan: Overview tab states \"12 - 13 May, 2027\", T-0 week w/c 10.05.2027. CS is on the floor — one pass past every partner booth per day, and a running note per partner of what broke and what they said.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Event",
    weeksOut: 0,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-05-12",
    dateEnd: "2027-05-13",
    notionUrl: "https://app.notion.com/p/3cc9551435718191bbf3dca1aa666736",
  },
  {
    id: "3cc95514357181c7b2e5f8f63731a607",
    milestone: "Lead and scan data delivered",
    detail: "HARD WALL — contractual, not a courtesy. 72h post-event for session and activation data, 24h for booth lead scanners.",
    event: "DTM27",
    workstream: "Passes & Access",
    ownerRole: "Passes & Access Owner",
    phase: "Wrap",
    weeksOut: -0.4,
    hardWall: true,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-05-15",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181c7b2e5f8f63731a607",
  },
  {
    id: "3cc955143571813c9d2edd0e41d5a330",
    milestone: "Follow-ups, thank-you emails and survey",
    detail: "Template 15. Dismantle is also this week. List any outstanding post-event deliverables with dates — never send this with them unlisted.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Wrap",
    weeksOut: -1,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-05-17",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc955143571813c9d2edd0e41d5a330",
  },
  {
    id: "3cc95514357181e2b516d70e2cad4b0f",
    milestone: "Rebooking opened with every partner",
    detail: "The plan's Partnership lane reads \"Rebook\" at W0, W-1 and W-2 — rebooking starts in event week, not after the wrap.",
    event: "DTM27",
    workstream: "Sales",
    ownerRole: "Sales Lead",
    phase: "Wrap",
    weeksOut: -1,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-05-17",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181e2b516d70e2cad4b0f",
  },
  {
    id: "3cc95514357181e497a1eebb954ea88b",
    milestone: "Event media shared; NPS",
    detail: "One Drive folder shared with every partner, with permission to reshare. Individual contracted videos — highlight reels, onsite interviews — run to their own windows, typically within one week.",
    event: "DTM27",
    workstream: "Marketing & Comms",
    ownerRole: "Marketing & Comms Owner",
    phase: "Wrap",
    weeksOut: -2,
    hardWall: false,
    inProjectPlan: true,
    partnerFacing: true,
    date: "2027-05-24",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181e497a1eebb954ea88b",
  },
  {
    id: "3cc95514357181f4bc23dd70d0b8e476",
    milestone: "Feedback calls held",
    detail: "Five questions in order: how it landed, did they get what they told us at onboarding, one thing to do better, can they quantify anything, will they give a testimonial. Then hand to the Sales Lead for rebooking with the evidence.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Wrap",
    weeksOut: -2,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-05-24",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181f4bc23dd70d0b8e476",
  },
  {
    id: "3cc95514357181f89290fd36b2d6cb68",
    milestone: "Post-event deliverables closed; invoices paid; partners Wrapped",
    detail: "LinkedIn posts, newsletter features, blog posts, reels, lookbook access, warm introductions — all closed and delivered, each with a named owner.",
    event: "DTM27",
    workstream: "CS spine",
    ownerRole: "CS Lead",
    phase: "Wrap",
    weeksOut: -4,
    hardWall: false,
    inProjectPlan: false,
    partnerFacing: true,
    date: "2027-06-07",
    dateEnd: null,
    notionUrl: "https://app.notion.com/p/3cc95514357181f89290fd36b2d6cb68",
  },
];
